name: Test azure deployment

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  IMAGE_NAME: nq-server

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: login docker.pkg.github.com
          username: irreal
          password: ${{ secrets.GH_TOKEN }}
      - uses: azure/webapps-container-deploy@v1
        with:
          app-name: 'nq-server'
          images: 'docker.pkg.github.com/nq-framework/nq-server/nq-server:latest'
      - name: Azure logout
        run: |
          az logout
